
int SCREEN_WIDTH = 640;
int SCREEN_HEIGHT = 640;


int TILE_WIDTH = 32;
int TILE_HEIGHT = 32;

const int TOTAL_TILES = ( SCREEN_WIDTH / TILE_WIDTH ) * ( SCREEN_HEIGHT / TILE_HEIGHT );

int PLAYER_SPEED = 2;